### ISSUE TITLE
Device does not scroll out of the box

### ISSUE THREAD

**Issue by hydrox24** [enderfusion/doomscroller#6]
Doomscroller pairs but does not scroll on Android 14 (S22; SM-S901E) out of the box.

**Comment by hydrox24** [comment]
Fixed the problem by building and uploading the firmware ([3483f93](https://github.com/enderfusion/doomscroller/commit/3483f9376262cf69b512dbc1483ca5d79fa64798), done on MacOS 14) and performing a magnetic reset (by swiping the magnet along the back from the D to the R).

I tried a magnetic reset alone first, and that did not fix the problem. It still paired but did not scroll.

**Comment by andrewmccalip** [comment]
Before pairing, try resetting it first by swiping the magnet over the back of the PCB. It likes to have a fresh reboot before pairing.  Also perform a reset *after* pairing as well. I've found that to be critical.
